const IpcEvent = {

  TOGGLE_FULLSCREEN: 'TOGGLE_FULLSCREEN',
  SET_FULLSCREEN: 'SET_FULLSCREEN',

  GET_EDITOR_STATUS: 'GET_EDITOR_STATUS',
  GET_EDITOR_STATUS_REPLY: 'GET_EDITOR_STATUS_REPLY',

  SET_EDITOR_STATUS: 'SET_EDITOR_STATUS',

  NEW_MARKDOWN: 'NEW_MARKDOWN',
  OPEN_MARKDOWN: 'OPEN_MARKDOWN',
  SAVE_MARKDOWN: 'SAVE',
  SAVE_AS_MARKDOWN: 'SAVE_AS_MARKDOWN',
  QUIT: 'QUIT',
};

export default IpcEvent;
